### PR TITLE
[NTV-199] Minor design tweaks to new project page

### PR DESCRIPTION
**Pull request by singhhari**
# 📲 What / 🤔 Why

During QA a few small design issues were spotted. This PR will address those design updates which include:
- adding a shadow to the project navigation selector view bottom border
- remove bottom border from navigation bar
- adjusting margins on the FAQs cells
- eliminating a background color from the image in Ask A Question cells
- update navigation bar color to white

# ✅ Acceptance criteria

- [ ] Verify each of the design tweaks mentioned above are addressed. The following tickets have a comment with each referenced update: 

[NTV-195](https://kickstarter.atlassian.net/browse/NTV-195)
[NTV-236](https://kickstarter.atlassian.net/browse/NTV-236)
[NTV-199](https://kickstarter.atlassian.net/browse/NTV-199)

### CODE REVIEW

**Review by msadoon — CHANGES_REQUESTED** [review]
Mostly changes are good, few things I noticed:

1. Based on [this](https://www.figma.com/file/Vk262JvQlfddgdkfXN0rx0/Native%3A-Project-Page-C5-2021?node-id=166%3A5281) design of the shadow, the drop shadow could use some work:


Also, things mentioned in the risks pr can be addressed in this UI tweaks ticket. Tip: merge that branch into this one first, to avoid merge conflicts.
2. navigation selector cutoff in landscape (especially evident on iPad, even in portrait)
iPhone 8, 14.5

iPad 12.9 Pro 4th gen, 14.5 (portrait, landscape)


Also evident in risks from prev pr:


Tip: run both iPhone and iPad quickly and see if changes look like designs above.

Overall though, its' looking pretty good most of the requested changes are here, just a few odds/ends.

**Comment by msadoon** [comment]
Found that the alignment on iPad for the cells and disclaimer cells for (faqs, risks and env commitments) are not aligned. I know we don't have designs for iPad, but maybe double check with design?

**Comment by singhhari** [comment]
> Mostly changes are good, few things I noticed:
> 
> 1. Based on [this](https://www.figma.com/file/Vk262JvQlfddgdkfXN0rx0/Native%3A-Project-Page-C5-2021?node-id=166%3A5281) design of the shadow, the drop shadow could use some work:
> 
> 
> 
> Also, things mentioned in the risks pr can be addressed in this UI tweaks ticket. Tip: merge that branch into this one first, to avoid merge conflicts. 2. navigation selector cutoff in landscape (especially evident on iPad, even in portrait) iPhone 8, 14.5  iPad 12.9 Pro 4th gen, 14.5 (portrait, landscape)   Also evident in risks from prev pr: 
> 
> Tip: run both iPhone and iPad quickly and see if changes look like designs above.
> 
> Overall though, its' looking pretty good most of the requested changes are here, just a few odds/ends.

Adjusted the shadow to be darker and a bit lower than the purple underline so it's easier to see. Also updated the inset I applied to the project navigation selector view so it's not visible regardless of device or orientation. I didn't want to do anything to make the change globally via tableview.separatorStyle so I'm applying an arbitrarily large inset instead and only affecting a single file.

Furthermore, I'm centering the project navigation selector view on iPad similar to the sorting UI on Discover and supporting landscape with some tweaks to the leading and trailing anchors. I also fixed the alignment on the cells; that was occurring because I was applying layout insets to the root stack view instead of the cells content view. 

I think all the UI issues appear to be resolved now, let me know if you see anything I missed.

**Comment by singhhari** [comment]
Merged this by accident but reverted on the feature branch and raised another PR with updates:

https://github.com/kickstarter/ios-oss/pull/1634

**Pull request merged**
