### PR TITLE
[WEB-983] Prelaunch Page Existing Project Page UI

### PR DESCRIPTION
**Pull request by msadoon**
# 📲 What

We want to enabled prelaunch projects to show a different UI to what is there now (looks broken.)

# 🤔 Why

Deeplinks are used in marketing campaigns to display projects to the user in-app. Those in-app projects are sometimes prelaunch, so they have no backer/pledge/comments/updates info. 

As of now prelaunch project deeplinks open (sometimes) in the app. We want to make them always open in-app and fix-up the UI to display the project page as intended [design](https://www.figma.com/file/Wt14jhetT6UVq0HpzMtXFe/Native-Pre-Launch?node-id=85%3A1451&t=fQg5l15MgXPswMlo-0).

# 🛠 How

Few pieces here, mainly related to the project's `displayPrelaunch` boolean. Previously `AppDelegate` was routing to Safari when that flag was true. It should now route in-app.

Needed Project `watchesCount` GQL property to be included in project fragment.

Update of Strings.

The main way we save the project is to reuse the `WatchProjectViewModel` in the `ProjectNavigationSelectorView`. We have the `PledgeCTAContainerView` pass the new `prelaunch` `PledgeCTAType` to that view via delegation - if the button click is from the pledge cta. If not we listen for a notification from the navigation selector when project saves there.

That's the cool part, we reuse a lot of existing code and keep the two views nicely in sync.

A minor bug was fixed within the project page, which on orientation change was showing cached images that were directly updated in the table before sections changed from Overview to another tab. So if you loaded a project and immediately changed the orientation, the overview tab shows images that should only be shown in the campaign tab. So nice quick fix there.

# 👀 See

| Before 🐛 | After 🦋 |
| --- | --- |
|  | below |

https://user-images.githubusercontent.com/4282741/226364419-903f38c9-f864-4820-9de1-6a163656bd38.mp4

# ✅ Acceptance criteria

- [x] Open a prelaunch project page in-app and see that it displays based on designs above.
- [x] Ensure saving works accurately on prelaunch projects and is reflect
- [x] Ensure existing non-prelaunch projects open with correct cta banner state (ie. pledge, manage, fix, retry, view rewards, view your rewards.)

# ⏰ TODO

- [x] Project page design update based on `displayPrelaunch` flag

### CODE REVIEW

**Comment by nativeksr** [comment]
### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| Library/ViewModels/ProjectNavigationSelectorViewModel.swift:59:1 | warning: (indent) Indent code in accordance with the scope level. |
| Library/ViewModels/ProjectNavigationSelectorViewModel.swift:60:1 | warning: (indent) Indent code in accordance with the scope level. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by scottkicks — CHANGES_REQUESTED** [review]
Nice work! Noticed a bug when going to profile to view the saved prelaunch project.
- The number of saved projects doesn't update
- The list of saved projects is not updating until forcing a pull-to-refresh (maybe that's a known one)
Simulator Screen Recording - iPhone 13 Pro - 2023-03-22 at 09 24 38

**Comment by msadoon** [comment]
> Nice work! Noticed a bug when going to profile to view the saved prelaunch project.
> 
>     * The number of saved projects doesn't update
> 
>     * The list of saved projects is not updating until forcing a pull-to-refresh (maybe that's a known one)
>       Simulator Screen Recording - iPhone 13 Pro - 2023-03-22 at 09 24 38
>             
>               [
>                 
>               
>                   Simulator Screen Recording - iPhone 13 Pro - 2023-03-22 at 09 24 38
>                 ](https://user-images.githubusercontent.com/110618242/226953748-404c2f96-5572-4190-82cb-caf9e94b211f.gif)
>               
>               
>                 
>                   
>                     
>                   
>                   
>                     
>                     
>                   
>                 
>                 [
>                   
>                     
>                   
>                 ](https://user-images.githubusercontent.com/110618242/226953748-404c2f96-5572-4190-82cb-caf9e94b211f.gif)
> 
> 
> Also, I'm still reviewing the string translation updates. It might be easier to put changes like that in a separate PR in the future to keep these smaller.

Ok, yea good point, just given the timelines though wanted this quickly merged with Strings. Plus the Strings are related to the context here.

Also regarding the saved projects not updating until refreshed -- documented it [here](https://kickstarter.atlassian.net/browse/MBL-670).

**Pull request merged**
