### PR TITLE
Facebook SDK update

### PR DESCRIPTION
**Pull request by bormind**
# What

Upgrade of the Facebook SDK framework to version 4.24.0

# Why

Some of the Facebook API we are using has been deprecated. We have to upgrade to new SDK to be UpToDate with the FB APIs  

# How

- Downloaded latest version of the SDK. 
- Replaced FBSDKCoreKit.framework, FBSDKLoginKit.framework in the Frameworks directory with new ones.
- Added Bolts.framework file (This is new dependency in the SDK)
- Added Bolts.framework link library to all targets in the project that use Facebook SDK

# See 👀

[Trello](https://trello.com/c/uav26jmW/525-facebook-graph-api-upgrade-ios)

# TODO ⏰

Not in the ios-oss source code, but we have to move our backend code to using new FB APIs as well

### CODE REVIEW

**Comment by bormind** [comment]
I see tests are failing on circleci Investigating..

**Comment by justinswart** [comment]
@bormind try merging `master` 👍

**Comment by bormind** [comment]
Didn't help

**Comment by justinswart** [comment]
@bormind I had a quick look at your branch, it looks like you may have accidentally committed `ios-ksapi` as a subproject, we've removed this from `Frameworks/ios-ksapi` because `KsApi` is now a framework in the main app repo.

Also, there were two duplicates of `Runes` and `Result` which I removed, I think this was due to a merge with us moving frameworks around at the same time.

If you like you can cherry-pick my commit [here](https://github.com/kickstarter/ios-oss/commit/6fff72f750c914f9beb3593427855f0d6e636852) on to your branch and it should fix circle.

**Comment by bormind** [comment]
Thanks!

**Pull request merged**
