### PR TITLE
updates imgix urls with cloudflare ones

### PR DESCRIPTION
**Pull request by warrenwegs**
# 📲 What

Replaces any imgix urls with cloudflare equivalents.

# 🤔 Why

We are no longer using imgix for serving/transforming images, only cloudflare.

# 🛠 How

These urls should just work

# 👀 See

Trello, screenshots, external resources?

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# ♿️ Accessibility 

- [ ] Tap targets use minimum of 44x44 pts dimensions
- [ ] Works with VoiceOver
- [ ] Supports Dynamic Type 

# 🏎 Performance

- [ ] Optimized Blended Layers (screenshots)

# ✅ Acceptance criteria

- [ ] Steps to test this feature
- [ ] Environment to test on
- [ ] Issues to look out for

# ⏰ TODO

- [ ] Got planned refactors to come
- [ ] Will add more tests
- [ ] Need feedback on a design

### CODE REVIEW

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| KsApi/models/templates/ProjectTemplates.swift:29:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:30:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:66:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:67:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:67:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:68:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:68:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:69:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:69:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:70:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:77:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:78:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:78:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:79:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:79:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:80:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:80:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:81:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:81:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:82:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:82:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:83:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:96:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:97:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:97:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:98:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:98:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:99:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:99:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:100:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:105:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:106:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:106:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:107:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:107:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:108:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:108:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:109:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:109:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:110:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:135:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:136:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:136:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:137:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:144:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:145:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:145:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:146:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/ProjectTemplates.swift:154:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/ProjectTemplates.swift:155:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/UserTemplates.swift:27:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/UserTemplates.swift:28:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/UserTemplates.swift:28:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/UserTemplates.swift:29:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/UserTemplates.swift:29:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/UserTemplates.swift:30:1 | warning: (indent) Indent code in accordance with the scope level. |
| KsApi/models/templates/UserTemplates.swift:30:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |
| KsApi/models/templates/UserTemplates.swift:31:1 | warning: (indent) Indent code in accordance with the scope level. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by amy-at-kickstarter** [comment]
Commit [d110185](https://github.com/kickstarter/ios-oss/pull/2017/commits/d110185f336781b5b3d18db0ed45b83ba5599d39) looks good, but also looks like another commit got pulled in here? Updating with merge to see if that fixes it.

**Comment by warrenwegs** [comment]
@amy-at-kickstarter I had to redo these replacements so the commit history got a bit mixed up earlier. It's correct now and should just be my commits and main branch merge ins

**Comment by amy-at-kickstarter** [comment]
@warrenwegs Ah, don't bother with putting a PR on `ios-private`. It's a shadow copy of this repo that we mechanically update when we make a releases, so you can safely ignore it.

**Review by amy-at-kickstarter — APPROVED** [review]
LGTM 👍

**Pull request merged**
