### PR TITLE
Add new header to readme

### PR DESCRIPTION
**Pull request by dannyalright**
# 📲 What

Replace the old green wordmark with the new green app icon (#707).

# 🤔 Why

- Old green is going away
- Why not show off the app icon a lil

# 🛠 How

Changing the SVG to a PNG (because of shadows).

# 👀 See

| Before 🐛 | After 🦋 |
| --- | --- |
| before | after |

# 📝 Notes

Added @justinswart as a reviewer as he added the logo originally and has been dealing with my app icon madness.

### CODE REVIEW

**Comment by justinswart** [comment]
Hey @dannyalright I'm actually in favour of keeping the wordmark and maybe just changing the colour? Unless you have strong feelings about replacing it with the icon?

**Comment by dannyalright** [comment]
Copy that.

No strong feelings—I was going for more of the app vibe over the company vibe. I'll update the colour of the wordmark, maybe shrink it a bit, and then update the PR.

**Comment by dannyalright** [comment]
how's that, @justinswart ?

**Comment by justinswart** [comment]
Yeah I like that - do you want to open one on https://github.com/kickstarter/android-oss too, that repo is currently the same as this one?

@eoji you dig?

**Comment by eoji** [comment]
yeah @dannyalright and I are pairing on the new icon tomorrow AM!

**Pull request merged**
