### PR TITLE
Make Storyboard.instantiate more implicit styled

### PR DESCRIPTION
**Pull request by frootloops**
What do you think about it?

### CODE REVIEW

**Comment by mbrandonw** [comment]
This is definitely interesting! It's kinda similar to what we do in our api client https://github.com/kickstarter/ios-ksapi/blob/master/KsApi/Service.swift#L511-L527, where the generic parameter `M` is used only in the return value, and so we rely on type-inference at the call site.

We'll think about it a bit more and see if it makes sense for us.

Thanks!

**Comment by frootloops** [comment]
@mbrandonw cool! Also why do you use `self.` notation so often? Even when it's not necessary. Is it some kind of your style guide?

**Comment by mbrandonw** [comment]
@frootloops  Yeah, we like to use `self.` everywhere because it's just clearer to us what the scoping is.

**Comment by mbrandonw** [comment]
We would enforce it with a swiftlint rule if we could...

**Comment by frootloops** [comment]
@mbrandonw I see! Thanks for publishing the project it helps me a lot to learn about reactive stuff :)

**Pull request closed without merging**
