### PR TITLE
Upload screenshots to Screenshotbot!

### PR DESCRIPTION
**Pull request by tdrhq**
# 📲 What

Hi @justinswart, @singhhari 

Once this PR is merged (plus some extra stuff, which I'll explain in a second), you'll get Screenshotbot reports on your PRs!

Here's an example PR: https://github.com/tdrhq/ios-oss/pull/90.

At this point it does not change the behavior with your tests, a screenshot change will always fail your tests, and you still have to manually record any changes for the test to pass. We'll make that final change once you're confident with the Screenshotbot workflow. i.e. In a few weeks time you'll never have to record screenshots again, just trust Screenshotbot to notify you on PRs. (I realized I might need some tweaks to FBSnapshotTestCase for this too.)

Few changes needed on your end: you'll have to add the Screenshotbot marketplace app: https://github.com/marketplace/screenshotbot (you don't have to grant permissions for the entire Kickstarter organization, just the ios-oss repo, which is open source anyway) Second, you'll need to set up the SCREENSHOTBOT_API_KEY and SCREENSHOTBOT_API_SECRET environment variables in your CircleCI builds. I'll send that over email.

PS. It's possible there are bugs in the circle config. I tested this on a heavily modified version of the config so that I could test it with my limited CircleCI capacity. I'm sure it's all fixable though.

cc @Arkariang

### CODE REVIEW

**Comment by justinswart** [comment]
@tdrhq Hey thanks for adding this! We have our CircleCI configured to run tests on forks so I'm not sure why this didn't run, I'll look into it 👍

**Comment by tdrhq** [comment]
@justinswart Those builds seem to be taking a while, probably failed? Could you let me know what the failure is? (I don't think I have access to the build links)

**Comment by justinswart** [comment]
@tdrhq Thanks again for this but we're just realistically not likely to get to this any time soon, will get in touch if anything changes in that regard but going to close this for now.

**Comment by tdrhq** [comment]
@justinswart No worries, let me know if anything changes, and I'm happy to help you integrate Screenshotbot

**Pull request closed without merging**
