### PR TITLE
[NTV-287] Updating PerimeterX to 1.16.3-doctor via Carthage

### PR DESCRIPTION
**Pull request by singhhari**
# 📲 What + 🤔 Why

A bug report came through Support Dev where a user was being presented with a press and hold challenge multiple times in a row. Our PerimeterX colleagues suggested that we upgrade our SDKs for both apps to benefit from some bug fixes.

# 🛠 How

Updated our Cartfile with the new version number and added the xcframework to Build Phases in the project settings.

# ✅ Acceptance criteria

- [ ] Run the carthage boostrap script and verify the project is building + running.

### CODE REVIEW

**Review by msadoon — CHANGES_REQUESTED** [review]
Tests are failing and I'm not sure why the framework it seems like is added directly into the project files, when they should be added through the Build Settings/Phases where the other frameworks have been added.
Will re-review tmr morning, just wrapping my comments query pr.

**Comment by singhhari** [comment]
> Tests are failing and I'm not sure why the framework it seems like is added directly into the project files, when they should be added through the Build Settings/Phases where the other frameworks have been added. Will re-review tmr morning, just wrapping my comments query pr.

Yep noticed the failures and re-ran to observe what was going on with the CI. I changed the approach in the second commit and dragged the frameworks (one for each architecture, two total) directly into Build Phases instead of the xcframework.

**Comment by singhhari** [comment]
So adding the xcframework to the ksapi target seems to have resolved the failures. Let me know if something looks funny with the changes I made to the input/output lists or build phases.

**Review by msadoon — APPROVED** [review]
Yep, I tried using 1.16.3-doctor and 1.16.3 in a separate branch and tests are failing on CI, this is a good approach, just curious why line 332 and 335 list the framework twice, but doesn't seem to be a huge deal, main thing is its' working.

Good to go!

**Comment by singhhari** [comment]
> Yep, I tried using 1.16.3-doctor and 1.16.3 in a separate branch and tests are failing on CI, this is a good approach, just curious why line 332 and 335 list the framework twice, but doesn't seem to be a huge deal, main thing is its' working.
> 
> Good to go!

Ah yeah that's because there is a separate framework for two distinct architectures. I imagine the non Carthage approach to this is way cleaner :/

**Pull request merged**
