### PR TITLE
[NTV-297] [NTV-292] Project Navigation Polish - Review after NTV-295

### PR DESCRIPTION
**Pull request by msadoon**
# 📲 What

There were a number of small issues found to be blockers before release: 

1.) Font size was wrong
2.) Larger iPhone sizes showing icons too close to bezel.
3.) Larger accessibility sizes and fonts breaking the navigation selector in various ways.
4.) Tabs text underline should be wider than text.
5.) Tabs should be flush and with edges and fully visible when tapped.
6.) Project header cell padding (18 all around title).
7.) Navigation selector top space 17, bottom space 17 (even spacing).

# 🤔 Why

Improve UX experience. [Designs](https://www.figma.com/file/Ke3Sfd9QK5VpV4HoDKXYWG/Native%3A-Project-Page-C6-2021?node-id=242%3A5548).

# 🛠 How

Several minor padding/constraints updates. Evident in code.

# 👀 See

Before 🐛 

https://user-images.githubusercontent.com/4282741/145084058-487c43ac-225d-4f7f-a2b2-71f551c31060.mp4

After 🦋 

https://user-images.githubusercontent.com/4282741/145083757-41cb1f36-c46c-4a39-8662-c86da386d5ba.mp4

# ♿️ Accessibility 

- [x] Change language and display text size and tab selector should be fully visible including all text (or as much fits on the screen width), along with blue underline, and grey border. Selecting tabs does not act janky, or differently between languages/phone/ipad/font sizes.

# ✅ Acceptance criteria

- [x] Ensure all listed above are fixed on iPad and iPhone.
  - Note on no. 5 spacing uneven on top only for non-notch phones on landscape. Should work for all iPhones in portrait, iPads in any orientation. (Verifed by product as okay.)
  - Also on large text sizes on different languages (spanish for example), the underline will not be exactly aligned on landscape iPhone. Not perfect, but good enough for release, I remember product saying that we don't need to perfectly support really large text sizes. It all still works for all scrolling cases.

### CODE REVIEW

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by singhhari — APPROVED** [review]
Nice job on this. I tested with German and the larger font sizes, didn't see any issues with the navigation selector. lgtm!

**Comment by msadoon** [comment]
I'm not certain why the coverage report says on `feature/new-project-page` is 88.92% in this report. The previous PR that was merged into `feature/new-project-page` lists the total coverage when the last commit of that [pr](https://github.com/kickstarter/ios-oss/pull/1644)) was merged as 84.92%. Which matches the coverage offered by the last commit of this pr. That makes sense because you can see this pr only 100+ lines are added, and the tests for `ProjectPageViewController` and `ProjectNavigationSelectorView` are the only ones re-recorded.

Last commit merged to main shows a coverage of 85.29%. So this pr merged into `feature/new-project-page` will drop the coverage by 0.37% when `feature` is merged to `main`.

If we look at this coverage [report](https://app.codecov.io/gh/kickstarter/ios-oss/compare/1645/commits), we see a 4% drop for this [commit](https://codecov.io/gh/kickstarter/ios-oss/commit/8425214679f68383c570e8ccb2b937badf08e646/). Which this drop in coverage can be attributed to, all the other coverage changes in the report are balanced out. But I suspect its' because we removed some old screenshots that were renamed and never cleaned up.

I still don't know for certain, but if 84.92% is an acceptable amount of total coverage on `main` I can merge this pr.

**Comment by msadoon** [comment]
Ok, so regened the coverage report by pushing an empty commit into the `feature/new-project-page` branch and merging the branch in here. Now the coverage report is showing 0% increase/decrease in coverage which is what makes sense given the few changes here.
Merging.

**Pull request merged**
