### PR TITLE
[MBL-1860] PLOT String Translations

### PR DESCRIPTION
**Pull request by scottkicks**
# 🤔 Why

There's new copy being added for our PLOT feature.

# 🛠 How

- Run `make strings` and verify that all localized string files are updated with the correct strings.
- Note that this script pulls in all of the latest string updates, so a few in this PR aren't relevant to PLOT.

# ⏰ TODO

- [x] Inform the team that new strings are accessible and ready to be used instead of hard coded strings.

### CODE REVIEW

**Review by jovaniks — APPROVED** [review]
Cool

**Comment by scottkicks** [comment]
@jovaniks this will need to be updated with the changes I made to the web repo in Thursday. Once the translations team is done of course

**Review by amy-at-kickstarter — APPROVED** [review]
Approved, assuming those `png` changes are due to string changes for those tests?

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Pull request merged**
