### PR TITLE
[PAY-2142] Fix Deeplinks Not Routing From Braze

### PR DESCRIPTION
**Pull request by msadoon**
# 📲 What

Marketing reporting that deeplinks failed to route in-app after our upgrade of Appboy-iOS-SDK to Braze iOS SDK.
We went a few versions forward there from 4.3.2 to 5.5.0, and didn't fully test in-app deeplinking from PN's sent with Braze.

# 🤔 Why

Marketing campaigns blocked from being effective if content cannot be directed for all supported deeplinks.

# 🛠 How

Turns out we never handled the Braze deeplink in our existing implemention where we decode the payload from Braze. `AppDelegateViewModel` `line  329` `PushEnvelope` has a `aps` case that contains an `alert` property which matches what's coming from Braze's payload, but the actual URL in braze's payload was a separate key called `ab_uri`. This key is not decoded.

So...I'm not sure how this ever worked, unless it was by accident.

Now there is a `BrazePushEnvelope` that handles all `ab_uri`'s coming from the system `userNotificationCenter(didRecieve, withCompletionhandler)` delegate method.

there are some `.pbxproj` settings related to code-signing that are okay to have in because they specify the provisioning which is required by our CI to match the build type (alpha/beta/debug) with the profiles found on `ios-certificates`

Note:
In-app notifications are still not working as expected. The issue is that `ABKInAppMessageControllerDelegate` is not being triggered, but the in-app notification is coming in as a PN through `UNUserNotificationCenterDelegate`. Suggestion for finding the fix here is to remove `Segment-Appboy-SDK`, integrate with `Appboy_SDK` not `Braze_iOS_SDK` then replace `Appboy_SDK` with `Segment-Appboy-SDK`.

Made a separate ticket (NTV-647) for this.
1. Start [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/). Once it's complete, test pn's work and integrate for In-app notifications.
2. [Troubleshooting](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/troubleshooting/#impressions)
3. [Sample](https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/InAppMessage/BrazeInAppMessageSample/BrazeInAppMessageSample/AppDelegate.m) with vanilla In-app notifications (no push notifications)

# 👀 See

Before 🐛 

https://user-images.githubusercontent.com/4282741/214084917-df5a69cf-e7a1-4f2e-8703-c84773cd7808.MP4

After 🦋

https://user-images.githubusercontent.com/4282741/214081986-21719baf-41f6-4680-89a8-0665f5ce2ab3.MP4

# ✅ Acceptance criteria

- [x] Ensure deeplinks route to their destination in app. Test a few from this [list](https://app.getguru.com/card/cqpagX7i/Sample-iOS-Push-NotificationsDeeplinks-Simulator-Setup). That's also the list that shows how to set up the project to accept deeplinks.

# ⏰ TODO

- [x] Ensure first install deeplinks appear on device, right now they fail to appear from Braze.
- [x] Ensure `base.xcconfig` and `.xcodeproj` related changes are not persisted unless they are file adds.
- [ ] Ensure in-app messages still come through.

### CODE REVIEW

**Comment by nativeksr** [comment]
### SwiftFormat found issues:

| File | Rules |
| ---- | ----- |
| KsApi/lib/KsApiNotification.swift:5:1 | warning: (wrap) Wrap lines that exceed the specified maximum width. |


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by msadoon** [comment]
> ### SwiftFormat found issues:
> File 	Rules
> KsApi/lib/KsApiNotification.swift:5:1 	warning: (wrap) Wrap lines that exceed the specified maximum width.
> 
> Generated by 🚫 [Danger](https://danger.systems/)

Weird formatting issue, not sure why it's putting it on a newline.

**Review by scottkicks — COMMENTED** [review]
@msadoon Code looks good to me and the app runs normally. Wasn't able to test the deep-linking though because Braze isn't identifying my account.

**Comment by msadoon** [comment]
> @msadoon Code looks good to me and the app runs normally. Wasn't able to test the deep-linking though because Braze isn't identifying my account.

Noted, I can't seem to register a staging only Braze user for now. If you're okay with approving I can run through some deeplink tests omo, or pair to show you that deeplinks work.

**Comment by scottkicks** [comment]
@msadoon that'd be great. thanks. just throw some time on my calendar whenever.

**Review by scottkicks — APPROVED** [review]

**Pull request merged**
