### PR TITLE
[NT-2006][NT-2013] Update Dependencies Latest Version

### PR DESCRIPTION
**Pull request by msadoon**
# 📲 What

Updating some of our outdated frameworks on `ios-oss`. See _Why_ section for more detail.

# 🤔 Why

As part of regular maintanence keep these libraries up to date to not introduce regressions with new version of iOS and improve stability of dependencies.

Also moves the supported frameworks to using `XCFramework` which are supported in XCode 11+. Hopefully improving our build times on CI but also containing support for multiple frameworks (iOS, MacOS, WatchOS, etc...) in one.

Frameworks upgraded:
```
**xcframeworks**
AlamofireImage "4.1.0" -> "4.1.0" (Latest: "4.2.0") 
FirebaseAnalyticsBinary "7.4.0" -> "7.4.0" (Latest: "8.1.1") 
FirebaseInAppMessagingBinary "7.4.0" -> "7.4.0" (Latest: "8.1.0") 
ReactiveSwift "6.5.0" -> "6.5.0" (Latest: "6.6.0") 
FirebasePerformanceBinary "7.4.0" -> "7.4.0" (Latest: "8.1.0") 
FirebaseCrashlyticsBinary "7.4.0" -> "7.4.0" (Latest: "8.1.0") 
swift-sdk "v3.6.1" -> "v3.6.1" (Latest: "v3.8.0") 
FirebaseProtobufBinary "7.4.0" -> "7.4.0" (Latest: "7.6.0") 

**regular framework**
PerimeterX "1.13.9" -> "1.13.9" (Latest: "1.14.1")  
NOTE: This framework (above) did not need to be included in any target. App still builds and runs, all tests pass.
appcenter-sdk-apple "4.0.0" -> "4.0.0" (Latest: "4.1.1") 
appboy_ios_sdk_full "4.1.0" -> "4.1.0" (Latest: "4.3.0")
```

Frameworks to be upgraded (in a separate PR):
```
analytics-ios "4.1.2" -> "4.1.2" (Latest: "4.1.4")
appboy-segment-ios "4.0.0" -> "4.0.0" (Latest: "4.2.0")
facebook-objc-sdk "v6.5.2" -> "v6.5.2" (Latest: "v11.0.0") <==== MAJOR
stripe-ios "v18.0.0" -> "v18.0.0" (Latest: "21.6.0") <==== MAJOR
```

This PR does not resolve all of these outdated dependencies:

```
analytics-ios "4.1.2" -> "4.1.2" (Latest: "4.1.4")
appboy-segment-ios "4.0.0" -> "4.0.0" (Latest: "4.2.0")
facebook-objc-sdk "v6.5.2" -> "v6.5.2" (Latest: "v11.0.0")
stripe-ios "v18.0.0" -> "v18.0.0" (Latest: "21.6.0")
```

The `analytics-ios` update creates this issue on CI: 

The `appboy-segment-ios` introduces this issue while running `make bootstrap`:

The `stripe-ios` introduces build errors in the project, as it's a major version change, this is to be expected, but still investigating the issues.

The `facebook-objc-sdk ` is another major version change and is solved in this ticket. I'll reopen [that PR](https://github.com/kickstarter/ios-oss/pull/1528) once this ticket goes in. This will also likely solve the failure of `carthage outdated` command. 

Working to resolve these issues in a separate PR.

# 🛠 How

Run `carthage build --use-xcframeworks --platform iOS` after updating `Cartfile` frameworks to latest versions. (Except `facebook-objc-sdk`, `stripe-ios` and `appboy-segment-ios`).

Remove existing frameworks from all targets (but keep track of them), and using [these](https://github.com/Carthage/Carthage#migrating-a-project-from-framework-bundles-to-xcframeworks) instructions from Carthage upgrade add back in the frameworks as `xcframework`. 

For script phase in each target removed all frameworks in the input and output files if they were converted to `xcframework`. In `KsApi`, the entire phase was taken out, along with the input output files.

Every framework that is not an `xcframework` can be added in the same way.

Clean, build, run all schemas that do not correspond to test frameworks.

Update test targets like above adding in missing dependencies specific to tests by checking report navigator:
 when tests fail.

# 👀 See

Trello, screenshots, external resources?

Running `carthage outdated`:
**Note: Currently `carthage outdated` is failing on this PR because it can't run a `facebook-sdk` related shell command.**
I'm hoping that oonce we update facebook to `xcframework` (noted above), this issue will resolve itself.

| Before 🐛 | After 🦋 |
| --- | --- |
|  |  |

# ✅ Acceptance criteria

### Steps To Ensure All Targets Build and Run With XCFrameworks

_Base steps_ (Do this once, no need to repeat for every schema run below.)
- [ ] `rm -rf Carthage` from `ios-oss` directory
- [ ] `make bootstrap`

_For `Kickstarter-iOS` app target_
- [ ] Delete preexisting apps on simulator
- [ ] Delete all derived data
- [ ] Switch to `Kickstarter-iOS` schema
- [ ] Run clean `CMD+SHIFT+K`
- [ ] Run schema on any simulator `CMD+R`

_For `Kickstarter-Framework-iOS`, `Library-iOS`, `KsApi` target_
- [ ] Delete preexisting apps on simulator
- [ ] Delete all derived data
- [ ] Switch to corresponding schema
- [ ] Run clean `CMD+SHIFT+K`
- [ ] Switch to iPhone 8 (14.2) simulator
- [ ] Run tests `CMD+U` (should build and run tests, which confirms build works and tests succeed.)

### CODE REVIEW

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nativeksr** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Big PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by singhhari — APPROVED** [review]
Cloned a brand new repo, ran `make bootstrap`, compiled + ran the app and passed all tests. 
lgtm!

**Review by justinswart — COMMENTED** [review]
I see that we've kept the `Carthage` build phase around for some of the targets and some of the frameworks in the `xcfilelist`, how did you decide what to keep?

**Comment by msadoon** [comment]
> I see that we've kept the `Carthage` build phase around for some of the targets and some of the frameworks in the `xcfilelist`, how did you decide what to keep?

All the changes discussed and tried, but failed:
- Remove the `carthage-debug-copy.sh` script along with `Carthage` phase from `Library` and `Kickstarter-Framework-iOS`
- Removed related input/output files:


`Carthage` phase removed from `Kickstarter-Framework-iOS` failed running the `Kickstarter-iOS` app target. Here is the error:


`Carthage` phase removed from `Library-iOS` failed running the `KickstarterUITests` target. Here is the error:


- Remove the `Copy Files` phase from `Library` target failed because `KickstarterUITests` complains it's missing `Segment` for some reason:

**Comment by msadoon** [comment]
Maybe we can let this PR go through and once we move to SPM we can remove Carthage completely?

**Comment by msadoon** [comment]
Closing out this PR as we didn't end up resolving the `xcframework`s against the CI archive step (run locally with: `bundle exec fastlane itunes_gym`). [Thread](https://kickstarter.slack.com/archives/CG55BBBBL/p1624583100040000) for more investigation.

**Pull request closed without merging**
