### PR TITLE
Backer currency display

### PR DESCRIPTION
**Pull request by ifbarrera**
# What

Addresses a bug @eoji found where backed currency amounts weren't using the new currency preferences display rules.

# How

Just needed to add the new currency symbol logic to `String` amounts and update the currency formatting function used when displaying `backed` amounts.

# See 👀

test_usproject_ususer_nonuslocation_backer_projectlocation_us_usercurrency_us_userlocation_ca 2x
simulator screen shot - iphone 8 - 2018-11-15 at 13 37 25

simulator screen shot - clone 1 of iphone 8 - 2018-11-15 at 13 49 02

### CODE REVIEW

**Comment by justinswart** [comment]
I think this is unrelated to the PR but I noticed that the colour of the _pledged of_ text changes after the project is refreshed. Not sure if that is intentional? cc @dannyalright (keep an eye on my mouse cursor below)

**Comment by justinswart** [comment]
More testing with: user location: Barcelona, pref: HK$, US/USD Project:

| Pledge on project page  | Manage your pledge |
| ------------- | ------------- |
| screen shot 2018-11-19 at 2 42 47 pm | screen shot 2018-11-19 at 2 43 20 pm |

**Comment by justinswart** [comment]
Posted all my testing here, it all lgtm! I think the one comment about the text colour changing after project refresh can be dealt with separately. Adding blocked label till you're back 👍

**Comment by dannyalright** [comment]
> I think this is unrelated to the PR but I noticed that the colour of the _pledged of_ text changes after the project is refreshed. Not sure if that is intentional? cc @dannyalright (keep an eye on my mouse cursor below)

*Not* intentional. The decision of text being green/grey on the second row predates me and I don't feel strongly about it. So I think the fix should be applying whichever of the two colors is easier to implement across the board. I'll revisit as project page gets revamped in the near future.

**Comment by dannyalright** [comment]
Is it helpful to remove the conditional logic that changes the color now? Or is that easy to spot again when we fine-tune colors in the future?

**Comment by ifbarrera** [comment]
@dannyalright it's a little bit involved because we have to remove the tests and update all the screenshots. I've created a follow-up card so we can get to this next sprint: https://trello.com/c/YUYSZPi6/584-standardize-pledge-color-on-project-page

**Comment by ifbarrera** [comment]
[Currency Preferences on Project Pages](https://trello.com/c/rtycrU1H/997-currency-preferences-on-project-pages)

**Pull request merged**
